### ISSUE TITLE
Some Font Awesome icons not showing?

### ISSUE THREAD

**Issue by paulhibbitts** [erickjx/docsify-fontawesome#1]
Thanks so much for this great Docsify plugin, very handy!

I can't seem to have certain Font Awesome icons show on a page, and was wondering if I messed up the installation somehow etc.

For example, the following icons show as blank on my install (HTML source shows expected iclass etc.):

`:fas fa-pencil fa-fw:`
`:fas fa-pencil-square fa-fw:`
`:fas fa-support fa-fw:`

Here is my index file:
https://github.com/hibbitts-design/docsify-open-course-starter-kit/blob/master/docs/index.html

Thanks very much,
Paul

**Comment by erickjx** [comment]
Hi, i check this :

- fa-pencil > is pro icon:  [https://fontawesome.com/icons/pencil?style=solid](https://fontawesome.com/icons/pencil?style=solid)
- fa-pencil-square > is:  fa-pen-square 
- fa-support  > not exist [https://fontawesome.com/icons?d=gallery&q=support](https://fontawesome.com/icons?d=gallery&q=support)

**Comment by paulhibbitts** [comment]
Hi @erickjx , thanks very much for looking into that - `fa-pen-square` works like a charm. Looks like `fa-support` is an alias (https://fontawesome.com/v4.7.0/icon/life-ring) so perhaps that was the issue there.

Thanks again for your great plugin!
Paul

**Comment by timd19** [comment]
Hello - I am having issues displaying the brand fontawesome icons.

https://fontawesome.com/icons/aws?style=brands

When I use :fab fa-aws: it shows as a blank square box

but using other icons such as :fas fa-clipboard-check: works

Update: I figured it out - your example in your README 
<link rel="stylesheet" href="unpkg.com/@fortawesome/fontawesome-free/css/brands.css" />

I had to update the href to include //

<link rel="stylesheet" href="//unpkg.com/@fortawesome/fontawesome-free/css/brands.css" />

**Comment by erickjx** [comment]
Hi, i update example with this font..and work fine, enjoy...
