### ISSUE TITLE
Possibility to support SVG icons?

### ISSUE THREAD

**Issue by paulhibbitts** [erickjx/docsify-fontawesome#4]
All of my Docsify open source projects continue to benefit from this wonderful plugin, thank you @erickjx !

I was wondering if it would be possible to modify this plugin to take advantage of Font Awesome SVG icons? Thanks very much.

**Comment by erickjx** [comment]
I will view this enhancement  soon.

**Comment by paulhibbitts** [comment]
Thank you very much for considering that feature @erickjx ! BTW, I've been testing your current plugin with the in-progress Docsify v5 Previews and all is well so far. You can see a preview of my Docsify-This.net using Docsify v5 (and your Font Awesome plugin!) at https://v2.preview.docsify-this.net

**Comment by erickjx** [comment]
Hi again, SVG example done:
![imagen](https://github.com/user-attachments/assets/abfeff9c-7335-41de-87da-3b053e2af9a0)

**Comment by paulhibbitts** [comment]
This looks amazing @erickjx and will be a great new feature for the Docsify community! I will next test this out in my Docsify-This project and share how things go. Thanks again🙂

**Comment by paulhibbitts** [comment]
Thanks again for this new SVG icon support! Here is an example preview build of Docsify-This using Font Awesome Web Fonts, and then using SVGs:

https://v2.preview.docsify-this.net/?basePath=https://raw.githubusercontent.com/hibbitts-design/docsify-this-multiple-page-course-site/main&homepage=home.md&sidebar=true&loadSidebar=_sidebar.md&name=CPT-363&loadNavbar=_navbar.md&mergeNavbar=true&hide-credits=true&browser-tab-title=CPT-363#/schedule

https://v2.preview.docsify-this.net/?basePath=https://raw.githubusercontent.com/hibbitts-design/docsify-this-multiple-page-course-site/main&homepage=home.md&sidebar=true&loadSidebar=_sidebar.md&name=CPT-363&loadNavbar=_navbar.md&mergeNavbar=true&hide-credits=true&browser-tab-title=CPT-363&svg-icons=true#/schedule

Thanks again,
Paul

**Comment by erickjx** [comment]
Excellent congratulations.
